name: Bug Report
description: Something is broken or doesn't work as expected
labels: ['needs triage']
body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    options:
    - label: I have searched for existing issues (both open and closed)
      required: true
- type: textarea
  attributes:
    label: Describe the Bug
    description: A concise description of what you're experiencing.
  validations:
    required: true
- type: textarea
  attributes:
    label: Steps To Reproduce
    description: Steps to reproduce the behavior.
    placeholder: |
      1. In this environment...
      2. With this config...
      3. Run '...'
      4. See error...
  validations:
    required: false
- type: textarea
  attributes:
    label: Environment
    description: |
      examples:
        - **OS**: Ubuntu 22.04
        - **slskd**: 0.24.0
        - **Docker Install?**: Yes
        - **Filesystem**: ext4
        - **Hardware**: Raspberry Pi 5 4gb
    value: |
        - OS: 
        - slskd: 
        - Docker Install?: 
        - Filesystem: 
        - Hardware:
    render: markdown
  validations:
    required: true
- type: textarea
  attributes:
    label: Anything else?
    description: |
      Links? Screenshots? References? Anything that will give us more context about the issue you are encountering!
      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
