name: Feature Request
description: Suggest a feature for slskd
labels: ['needs triage']
body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    options:
    - label: I have searched for existing issues (both open and closed)
      required: true
- type: textarea
  attributes:
    label: Describe the Feature
    description: A concise description of the feature you'd like to be added.
  validations:
    required: true
- type: textarea
  attributes:
    label: Anything else?
    description: |
      Links? Screenshots? References? Anything that will give us more context about the feature you are suggesting!
      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
